<?php
/**
 * Created by PhpStorm.
 * User: taniguchi
 * Date: 2/7/15
 * Time: 14:17
 */
namespace nagoyaphp\doukaku8\Map;
class MapTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Map
     */
    protected $map;


    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->map = new Map();

    }

    public function testMap()
    {
        /*0*/ $this->check( [[0,1,2,2,4],[8,2,9,2,5],[6,9,0,7,6],[3,2,2,9,8],[2,1,0,6,5]], 25 );
    }

    private function check($input, $expect)
    {
        //配列が最終的に指定のPoint型のクラスの集合に変換されている事。
        $this->map->setValues($input);
        $result = $this->map->getPoints();
        $this->assertEquals(count($result), $expect, "要素数が一致していません");
    }

}
