<?php
/**
 * Created by PhpStorm.
 * User: taniguchi
 * Date: 2/7/15
 * Time: 14:17
 */
namespace nagoyaphp\doukaku8\Map;
class PointTest extends \PHPUnit_Framework_TestCase {

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testPoint()
    {
    }


}
