<?php
/**
 * Created by PhpStorm.
 * User: taniguchi
 * Date: 2/7/15
 * Time: 14:16
 */
namespace nagoyaphp\doukaku8\Utils;
class InputParserTest extends \PHPUnit_Framework_TestCase {

    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testDoukaku()
    {
        /*0*/ $this->check( "01224/82925/69076/32298/21065", [[0,1,2,2,4],[8,2,9,2,5],[6,9,0,7,6],[3,2,2,9,8],[2,1,0,6,5]] );
    }

    private function check($input, $expect)
    {
        $result = InputParser::parse($input);
        $this->assertEquals($result, $expect, "一致していません");
    }

}
